add-highlighter global/ show-whitespaces
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ wrap -word -indent

source "%val{config}/plugins/kakboard/kakboard.kak"
#hook global WinCreate .* %{ kakboard-enable }
