# Path to your oh-my-zsh installation.
export ZSH=$HOME/.zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# This theme might require Powerline Fonts
ZSH_THEME="miloshadzic"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(dirhistory zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

export TERM='xterm-256color'

xrdb -merge ~/.Xresources

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Display the linux logo
# (from http://www.deater.net/weave/vmwprod/asm/ll/ll.html)
#linuxlogo

#############
# Shortcuts #
#############

# git clone from github
function gcl () {
  git clone git@github.com:"${1}"
}

# git add patch
function gap () {
  git add --patch
}

# git status
function gs () {
  git status
}

# git remote
function gr () {
  git remote -v
}

# git push
function gp () {
  if [ -z "$1" ]; then; 1=origin; fi
  if [ -z "$2" ]; then; 2=master; fi
  git push $1 $2
}

function gf () {
  git fetch
}

# git pull
function gpull () {
  if [ -z "$1" ]; then; 1=origin; fi
  if [ -z "$2" ]; then; 2=master; fi
  git pull $1 $2
}

# Docker clean
function dc () {
  docker ps -q | xargs docker kill
  docker ps -aq | xargs docker rm
  docker images -f dangling=true -q | xargs docker rmi
}

function wifi () {
  wicd-curses
}

function fuck () {
  sudo $(fc -ln -1)
}

####################
# Dockerized Tools #
####################

PATH="$PATH:/home/retrohacker/Development/docker/.bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f /home/retrohacker/google-cloud-sdk/path.zsh.inc ]; then
  source '/home/retrohacker/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /home/retrohacker/google-cloud-sdk/completion.zsh.inc ]; then
  source '/home/retrohacker/google-cloud-sdk/completion.zsh.inc'
fi
